config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :flights, only: :index
  resources :transactions, only: %i[create new index]

  get "🛩", to: 'flights#index'

  root 'flights#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flight.rb
class Flight < ApplicationRecord
  validates :cost, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :destination, presence: true
  validates :origin, presence: true

  has_many :transactions, dependent: :destroy
end

app/models/saved_card.rb
class SavedCard < ApplicationRecord
  validates :card_type, presence: true
  validates :last_four_digits, length: { is: 4 }
  validates :token, presence: true

  has_many :transactions

  def to_s
    [card_type, last_four_digits].join(' ')
  end
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  validates :amount, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :email, presence: true # TODO: Consider format validation
  validates :payment_method_token, presence: true
  validates :ticket_count, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  belongs_to :flight
  belongs_to :saved_card, optional: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  def index
    @flights = Flight.all
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  def index
    @transactions = Transaction.includes(:flight).all
  end

  def new
    flight = Flight.find(params[:flight_id]) # Let it blow up if no flight found
    @transaction = flight.transactions.new
    @saved_cards = SavedCard.all
  end

  # TODO: Clean this action up a bunch.
  def create
    @transaction = Transaction.new(transaction_params)

    # TODO: Maybe not this here
    @transaction.payment_method_token = @transaction.saved_card.token if @transaction.saved_card

    ##### TODO: Cleanup
    if @transaction.valid?
      if @transaction.purchase_via_pmd?
        spreedly_transaction = deliver_to_receiver(@transaction)
      else
        spreedly_transaction = spreedly_env.purchase_on_gateway(
          ENV['gateway_token'],
          @transaction.payment_method_token,
          @transaction.amount * 100,
          retain_on_success: @transaction.save_card?
        )
      end

      if spreedly_transaction.succeeded?
        @transaction.transaction_token = spreedly_transaction.token

        notice_msg = 'Enjoy your flight!'
        notice_msg << ' You purchased this using PMD.' if @transaction.purchase_via_pmd?

        if @transaction.saved_card
          notice_msg << ' You used a saved card to pay for this.'
        elsif @transaction.save_card?
          notice_msg << ' Your card has been saved for future purchases!'
          credit_card = spreedly_env.find_payment_method(@transaction.payment_method_token)

          @transaction.build_saved_card(
            last_four_digits: credit_card.last_four_digits,
            card_type: credit_card.card_type,
            token: credit_card.token
          )
        end

        @transaction.save!
        redirect_to transactions_path, notice: notice_msg
      else
        @saved_cards = SavedCard.all
        flash.now[:notice] = spreedly_transaction.message
        render :new
      end
    else
      @saved_cards = SavedCard.all
      render :new
    end
  end

  private

  def transaction_params
    params.require(:transaction).permit(
      :amount, :email, :flight_id, :payment_method_token, :purchase_via_pmd,
      :save_card, :saved_card_id, :ticket_count
    )
  end

  def spreedly_env
    @_spreedly_env ||= Spreedly::Environment.new(ENV['spreedly_environment_key'], ENV['spreedly_access_secret'])
  end

  def deliver_to_receiver(transaction)
    spreedly_env.deliver_to_receiver(
      ENV['third_party_receiver_token'],
      transaction.payment_method_token,
      headers: { "Content-Type": "application/json" },
      url: ENV['third_party_receiver_url'],
      body: {
        amount: transaction.amount,
        card_number: "{{credit_card_number}}",
        email: transaction.email,
        flight_id: transaction.flight_id,
        ticket_count: transaction.ticket_count
      }.to_json
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flights_navigation_link
    return 'Flights' if controller_name == 'flights' && action_name == 'index'
    link_to('Flights', flights_path)
  end

  def transactions_navigation_link
    return 'Transactions' if controller_name == 'transactions' && action_name == 'index'
    link_to('Transactions', transactions_path)
  end
end

app/helpers/flights_helper.rb
module FlightsHelper
  def display_flight_info(flight)
    "#{flight.origin} ➡️ #{flight.destination}"
  end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/flights/index.html.erb
<h2>Flights</h2>

<table>
  <thead>
    <th>From</th>
    <th></th>
    <th>To</th>
    <th>Cost</th>
    <th></th>
  </thead>
  <% @flights.each do |flight| %>
    <tr>
      <td><%= flight.origin %></td>
      <td>➡️</td>
      <td><%= flight.destination %></td>
      <td><%= number_to_currency(flight.cost, precision: 0) %></td>
      <td><%= link_to 'Buy Tickets!', new_transaction_path(flight_id: flight) %></td>
    </tr>
  <% end %>
</table>

<h3>BUY SOMETHIN' WILL YA!</h3>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>🛩Joe's Discount Aeroplane Travel</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <h1>Joe's Discount Aeroplane Travel!🛩</h1>
    <em>You Get What You Pay For©</em>
    <hr />

    <p>
      <%= flights_navigation_link %> |
      <%= transactions_navigation_link %>
    </p>

    <% flash.each do |type, msg| %>
      <div class='flash'>
        <%= msg %>
      </div>
    <% end %>

    <%= yield %>

  </body>
</html>

app/views/transactions/index.html.erb
<h2>Transactions</h2>

<table>
  <thead>
    <th>Email</th>
    <th colspan="3">Flight info</th>
    <th>Cost per Ticket</th>
    <th>Ticket Count</th>
    <th>Total Cost</th>
    <th>Saved Card for Future Use?</th>
    <th>Used Saved Card?</th>
    <th>Purchased Using PMD?</th>
    <th>Purchased at</th>
  </thead>
  <% @transactions.each do |transaction| %>
    <tr>
      <td><%= transaction.email %></td>
      <td><%= transaction.flight.origin %></td>
      <td>➡️</td>
      <td><%= transaction.flight.destination %></td>
      <td><%= number_to_currency(transaction.flight.cost, precision: 0) %></td>
      <td><%= transaction.ticket_count %></td>
      <td><%= number_to_currency(transaction.amount, precision: 0) %></td>
      <td><%= transaction.save_card? %></td>
      <td><%= !transaction.save_card? && transaction.saved_card.present? %></td>
      <td><%= transaction.purchase_via_pmd? %></td>
      <td><%= transaction.created_at %></td>
    </tr>
  <% end %>
</table>

app/views/transactions/new.html.erb
<script src="https://core.spreedly.com/iframe/express-2.min.js"></script>

<script>
  function initSpreedly(){
    SpreedlyExpress.init("<%= ENV['spreedly_environment_key'] %>", {
      "amount": "$" + document.getElementById('transaction_amount').value,
      "company_name": "Joe's Discount Aeroplane Travel",
      "sidebar_top_description": "You get what you pay for©",
      "name_label": "Cardholder's Name",
      "submit_label": "Buy Tickets Now!"
    }, {
      "email": document.getElementById('transaction_email').value
    });
  }

  SpreedlyExpress.onPaymentMethod(function(token, paymentMethod) {
    // Send requisite payment method info to backend
    var tokenField = document.getElementById("transaction_payment_method_token");

    tokenField.setAttribute("value", token);

    var masterForm = document.getElementById('new_transaction');
    masterForm.submit();
  });

  function setTotalAmount(){
    var ticketCount = document.getElementById('transaction_ticket_count').value;
    var totalCost = <%= @transaction.flight&.cost %> * ticketCount;
    var setAmount = document.getElementById('transaction_amount');
    setAmount.setAttribute("value", totalCost);
    document.getElementById('grand-total').innerHTML = "$" + totalCost;
  }

  function selectedSavedCard(){
    var savedCardId = document.getElementById('transaction_saved_card_id').value;
    var savedCardSubmitButton = document.getElementById('saved_card_submit_button');

    savedCardSubmitButton.disabled = (savedCardId == "" ? true : false);
  }
</script>

<h1>New Transaction</h1>

<%= form_for(@transaction) do |f| %>
  <% if @transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
      <% @transaction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    Flight: <%= display_flight_info(@transaction.flight) %>
    <%= f.hidden_field :flight_id, value: @transaction.flight_id %>
  </div>

  <div>
    Cost per Ticket: <%= number_to_currency(@transaction.flight.cost, precision: 0) %>
  </div>

  <div>
    Email: <%= f.text_field :email %>
  </div>

  <div>
    How many tickets you want?: <%= f.number_field :ticket_count, in: 1...10, onchange: 'setTotalAmount();' %>
  </div>

  <div>
    Total Cost: <div id='grand-total'></div>
  </div>

  <div>
    Save card for future use? <%= f.select :save_card, [['Yes', true], ['No', false]]%>
  </div>

  <div>
    Purchase Using PMD? <%= f.select :purchase_via_pmd, [['Yes', true], ['No', false]]%>
  </div>

  <% if @saved_cards.any? %>
    <div class="payment_option">
      Buy using a Saved Card:
      <%= f.select :saved_card_id, options_from_collection_for_select(@saved_cards, :id, :to_s), {include_blank: true}, onchange: 'selectedSavedCard();' %>
      <%= f.submit 'Buy with this saved card!', id: 'saved_card_submit_button', disabled: true %>
    </div>
  <% end %>

  <%= f.hidden_field :amount %>
  <%= f.hidden_field :payment_method_token %>
<% end %>

<% if @saved_cards.any? %>
  <p>OR</p>
<% end %>

<div class="payment_option">
  Buy with a fresh card:
  <button onmouseover="initSpreedly()" onClick="SpreedlyExpress.openView()">
    Enter New Payment Info
  </button>
</div>